[package]

name = "capital_larceny"
version = "0.0.1"
authors = ["Miranda <mirandaseitzmcleese@gmail.com>", "Jarrett <jarrettcolby@gmail.com>"]

[dependencies.piston2d-graphics]
git = "https://github.com/PistonDevelopers/graphics"